<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTGjICqE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTGjICqE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTGjICqE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTGjICqE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTGjICqE\App_KernelDevDebugContainer([
    'container.build_hash' => 'TGjICqE',
    'container.build_id' => 'b73d27b4',
    'container.build_time' => 1682998713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTGjICqE');
