<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UnHZN85Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UnHZN85' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UnHZN85'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campingRepository' => ['privates', 'App\\Repository\\CampingRepository', 'getCampingRepositoryService', true],
            'favorite' => ['privates', '.errored..service_locator.UnHZN85.App\\Entity\\Favorite', NULL, 'Cannot autowire service ".service_locator.UnHZN85": it references class "App\\Entity\\Favorite" but no such service exists.'],
            'randonneeRepository' => ['privates', 'App\\Repository\\RandonneeRepository', 'getRandonneeRepositoryService', true],
        ], [
            'campingRepository' => 'App\\Repository\\CampingRepository',
            'favorite' => 'App\\Entity\\Favorite',
            'randonneeRepository' => 'App\\Repository\\RandonneeRepository',
        ]);
    }
}
