<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JuF4hz9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.juF4hz9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.juF4hz9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participation' => ['privates', '.errored..service_locator.juF4hz9.App\\Entity\\Participations', NULL, 'Cannot autowire service ".service_locator.juF4hz9": it references class "App\\Entity\\Participations" but no such service exists.'],
        ], [
            'participation' => 'App\\Entity\\Participations',
        ]);
    }
}
