<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XP6KlT_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xP6KlT.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xP6KlT.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'randonnee' => ['privates', '.errored..service_locator.xP6KlT..App\\Entity\\Randonnee', NULL, 'Cannot autowire service ".service_locator.xP6KlT.": it references class "App\\Entity\\Randonnee" but no such service exists.'],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'randonnee' => 'App\\Entity\\Randonnee',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
