<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VSa_CZGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VSa.CZG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VSa.CZG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campingRepository' => ['privates', 'App\\Repository\\CampingRepository', 'getCampingRepositoryService', true],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'randonneeRepository' => ['privates', 'App\\Repository\\RandonneeRepository', 'getRandonneeRepositoryService', true],
        ], [
            'campingRepository' => 'App\\Repository\\CampingRepository',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'randonneeRepository' => 'App\\Repository\\RandonneeRepository',
        ]);
    }
}
