<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCamping4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oOPl47G.App\Entity\Camping' shared service.
     *
     * @return \App\Entity\Camping
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oOPl47G": it references class "App\\Entity\\Camping" but no such service exists.');
    }
}
