<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UnHZN85.App\Entity\Favorite' shared service.
     *
     * @return \App\Entity\Favorite
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UnHZN85": it references class "App\\Entity\\Favorite" but no such service exists.');
    }
}
