<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.juF4hz9.App\Entity\Participations' shared service.
     *
     * @return \App\Entity\Participations
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.juF4hz9": it references class "App\\Entity\\Participations" but no such service exists.');
    }
}
