<?php

namespace ContainerAArEZwD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRandonnee3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YOzwlmk.App\Entity\Randonnee' shared service.
     *
     * @return \App\Entity\Randonnee
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YOzwlmk": it references class "App\\Entity\\Randonnee" but no such service exists.');
    }
}
