<?php

namespace ContainerS4kf1zl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_I5zhxXOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.i5zhxXO' shared service.
     *
     * @return \App\Controller\MailingController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\ParticipationController::StatusChange()": the $mailing argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailingController". Did you forget to add a use statement?');
    }
}
