<?php

namespace ContainerS4kf1zl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STSOU0iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sTSOU0i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sTSOU0i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evenement' => ['privates', '.errored..service_locator.sTSOU0i.App\\Entity\\Evenement', NULL, 'Cannot autowire service ".service_locator.sTSOU0i": it references class "App\\Entity\\Evenement" but no such service exists.'],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'mailing' => ['privates', '.errored.LuaFI9F', NULL, 'Cannot determine controller argument for "App\\Controller\\EvenementClientController::participer()": the $mailing argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailingController". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'evenement' => 'App\\Entity\\Evenement',
            'mailer' => '?',
            'mailing' => '?',
        ]);
    }
}
