<?php

namespace ContainerS4kf1zl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P6kBKILService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p6kBKIL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p6kBKIL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'mailing' => ['privates', '.errored.i5zhxXO', NULL, 'Cannot determine controller argument for "App\\Controller\\ParticipationController::StatusChange()": the $mailing argument is type-hinted with the non-existent class or interface: "App\\Controller\\MailingController". Did you forget to add a use statement?'],
        ], [
            'entityManager' => '?',
            'mailer' => '?',
            'mailing' => '?',
        ]);
    }
}
