<?php

namespace ContainerTJmDkOI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OerXgdqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OerXgdq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OerXgdq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'camping' => ['privates', '.errored.arxHqGI', NULL, 'Cannot determine controller argument for "App\\Controller\\CampingController::favorite()": the $camping argument is type-hinted with the non-existent class or interface: "App\\Entity\\Camping".'],
            'favoritesRepository' => ['privates', '.errored.nkj_dEj', NULL, 'Cannot determine controller argument for "App\\Controller\\CampingController::favorite()": the $favoritesRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\FavoriteRepository".'],
        ], [
            'camping' => '?',
            'favoritesRepository' => '?',
        ]);
    }
}
