<?php

namespace ContainerTJmDkOI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ChApKRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._chApKR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._chApKR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator._chApKR.App\\Entity\\Utilisateur', NULL, 'Cannot autowire service ".service_locator._chApKR": it references class "App\\Entity\\Utilisateur" but no such service exists.'],
        ], [
            'user' => 'App\\Entity\\Utilisateur',
        ]);
    }
}
