<?php

namespace ContainerTJmDkOI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U0zw5yKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U0zw5yK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U0zw5yK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'camping' => ['privates', '.errored.3lymxy3', NULL, 'Cannot determine controller argument for "App\\Controller\\CampingController::show()": the $camping argument is type-hinted with the non-existent class or interface: "App\\Entity\\Camping".'],
        ], [
            'camping' => '?',
        ]);
    }
}
