<?php

namespace ContainerTJmDkOI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TYLmbrkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TYLmbrk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TYLmbrk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'camping' => ['privates', '.errored.1a34ioL', NULL, 'Cannot determine controller argument for "App\\Controller\\CampingController::edit()": the $camping argument is type-hinted with the non-existent class or interface: "App\\Entity\\Camping".'],
            'campingRepository' => ['privates', 'App\\Repository\\CampingRepository', 'getCampingRepositoryService', true],
        ], [
            'camping' => '?',
            'campingRepository' => 'App\\Repository\\CampingRepository',
        ]);
    }
}
