<?php

namespace ContainerTJmDkOI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublication3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mzJG0hG.App\Entity\Publication' shared service.
     *
     * @return \App\Entity\Publication
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mzJG0hG": it references class "App\\Entity\\Publication" but no such service exists.');
    }
}
