<?php

namespace Container3Z4LCmR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentaireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.17I6qek.App\Entity\Commentaire' shared service.
     *
     * @return \App\Entity\Commentaire
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.17I6qek": it references class "App\\Entity\\Commentaire" but no such service exists.');
    }
}
