<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N9Z5U5SService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n9Z5U5S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n9Z5U5S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participation' => ['privates', '.errored..service_locator.n9Z5U5S.App\\Entity\\Participations', NULL, 'Cannot autowire service ".service_locator.n9Z5U5S": it references class "App\\Entity\\Participations" but no such service exists.'],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationsRepository', 'getParticipationsRepositoryService', true],
        ], [
            'participation' => 'App\\Entity\\Participations',
            'participationRepository' => 'App\\Repository\\ParticipationsRepository',
        ]);
    }
}
