<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YXHExfGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YXHExfG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YXHExfG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campingController' => ['services', 'App\\Controller\\CampingController', 'getCampingControllerService', true],
            'campingRepository' => ['privates', 'App\\Repository\\CampingRepository', 'getCampingRepositoryService', true],
            'favoriteRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationsRepository', 'getParticipationsRepositoryService', true],
        ], [
            'campingController' => 'App\\Controller\\CampingController',
            'campingRepository' => 'App\\Repository\\CampingRepository',
            'favoriteRepository' => 'App\\Repository\\FavoriteRepository',
            'participationRepository' => 'App\\Repository\\ParticipationsRepository',
        ]);
    }
}
