<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Umb9AsNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Umb9AsN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Umb9AsN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'camping' => ['privates', '.errored..service_locator.Umb9AsN.App\\Entity\\Camping', NULL, 'Cannot autowire service ".service_locator.Umb9AsN": it references class "App\\Entity\\Camping" but no such service exists.'],
            'favoritesRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
        ], [
            'camping' => 'App\\Entity\\Camping',
            'favoritesRepository' => 'App\\Repository\\FavoriteRepository',
        ]);
    }
}
