<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KaZa9k9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KaZa9k9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KaZa9k9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'campingRepository' => ['privates', 'App\\Repository\\CampingRepository', 'getCampingRepositoryService', true],
        ], [
            'campingRepository' => 'App\\Repository\\CampingRepository',
        ]);
    }
}
