<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CaTM60iService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.caTM60i' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.caTM60i'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'randonneeRepository' => ['privates', 'App\\Repository\\RandonneeRepository', 'getRandonneeRepositoryService', true],
            'ratingRepository' => ['privates', 'App\\Repository\\RatingRepository', 'getRatingRepositoryService', true],
        ], [
            'randonneeRepository' => 'App\\Repository\\RandonneeRepository',
            'ratingRepository' => 'App\\Repository\\RatingRepository',
        ]);
    }
}
