<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGcdaQ_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tGcdaQ.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tGcdaQ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationsRepository', 'getParticipationsRepositoryService', true],
            'randonneeRepository' => ['privates', 'App\\Repository\\RandonneeRepository', 'getRandonneeRepositoryService', true],
        ], [
            'participationRepository' => 'App\\Repository\\ParticipationsRepository',
            'randonneeRepository' => 'App\\Repository\\RandonneeRepository',
        ]);
    }
}
