<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YOzwlmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YOzwlmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YOzwlmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'favoritesRepository' => ['privates', 'App\\Repository\\FavoriteRepository', 'getFavoriteRepositoryService', true],
            'randonnee' => ['privates', '.errored..service_locator.YOzwlmk.App\\Entity\\Randonnee', NULL, 'Cannot autowire service ".service_locator.YOzwlmk": it references class "App\\Entity\\Randonnee" but no such service exists.'],
        ], [
            'favoritesRepository' => 'App\\Repository\\FavoriteRepository',
            'randonnee' => 'App\\Entity\\Randonnee',
        ]);
    }
}
