<?php

namespace ContainerFI46xvA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I2ET6CTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i2ET6CT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i2ET6CT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateAsString' => ['privates', '.errored..service_locator.i2ET6CT.DateTime', NULL, 'Cannot autowire service ".service_locator.i2ET6CT": it references class "DateTime" but no such service exists.'],
        ], [
            'dateAsString' => 'DateTime',
        ]);
    }
}
