controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

delete_reservation:
  path: /reservations/delete/{id}
  controller: App\Controller\ReservationController::delete
