<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \App\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'idUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nomUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenomUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'emailUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'loginUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'mdpUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'imageUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'rankUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'telephoneUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresseUtilisateur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'idUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'nomUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'prenomUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'emailUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'loginUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'mdpUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'imageUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'rankUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'telephoneUtilisateur', '' . "\0" . 'App\\Entity\\Utilisateur' . "\0" . 'adresseUtilisateur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdUtilisateur(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUtilisateur();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUtilisateur', []);

        return parent::getIdUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUtilisateur(int $idUtilisateur): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUtilisateur', [$idUtilisateur]);

        parent::setIdUtilisateur($idUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomUtilisateur', []);

        return parent::getNomUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomUtilisateur(?string $nomUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomUtilisateur', [$nomUtilisateur]);

        return parent::setNomUtilisateur($nomUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenomUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenomUtilisateur', []);

        return parent::getPrenomUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenomUtilisateur(?string $prenomUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenomUtilisateur', [$prenomUtilisateur]);

        return parent::setPrenomUtilisateur($prenomUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailUtilisateur', []);

        return parent::getEmailUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailUtilisateur(?string $emailUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailUtilisateur', [$emailUtilisateur]);

        return parent::setEmailUtilisateur($emailUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginUtilisateur', []);

        return parent::getLoginUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginUtilisateur(?string $loginUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginUtilisateur', [$loginUtilisateur]);

        return parent::setLoginUtilisateur($loginUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdpUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdpUtilisateur', []);

        return parent::getMdpUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdpUtilisateur(?string $mdpUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdpUtilisateur', [$mdpUtilisateur]);

        return parent::setMdpUtilisateur($mdpUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUtilisateur', []);

        return parent::getImageUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUtilisateur(?string $imageUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUtilisateur', [$imageUtilisateur]);

        return parent::setImageUtilisateur($imageUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getRankUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRankUtilisateur', []);

        return parent::getRankUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setRankUtilisateur(?string $rankUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRankUtilisateur', [$rankUtilisateur]);

        return parent::setRankUtilisateur($rankUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneUtilisateur', []);

        return parent::getTelephoneUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneUtilisateur(?string $telephoneUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneUtilisateur', [$telephoneUtilisateur]);

        return parent::setTelephoneUtilisateur($telephoneUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseUtilisateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseUtilisateur', []);

        return parent::getAdresseUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseUtilisateur(?string $adresseUtilisateur): \App\Entity\Utilisateur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseUtilisateur', [$adresseUtilisateur]);

        return parent::setAdresseUtilisateur($adresseUtilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
