<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKcfOvGg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKcfOvGg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKcfOvGg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKcfOvGg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKcfOvGg\App_KernelDevDebugContainer([
    'container.build_hash' => 'KcfOvGg',
    'container.build_id' => 'a44e0594',
    'container.build_time' => 1682381609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKcfOvGg');
