<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAYxwqQN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAYxwqQN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAYxwqQN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAYxwqQN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAYxwqQN\App_KernelDevDebugContainer([
    'container.build_hash' => 'AYxwqQN',
    'container.build_id' => '141f5c32',
    'container.build_time' => 1682881405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAYxwqQN');
